# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - main  # Runs pipeline on main branch commits

variables:
  ACR_NAME: "typescriptimage"  # Replace with your ACR name
  IMAGE_NAME: "my-app"
  TAG: "$(Build.BuildId)"  # Unique build identifier
  RESOURCE_GROUP: "linux-agent_group"
  MANAGED_IDENTITY_NAME: "a717f3e4-b10b-4a70-b565-a471734765b7"  # User Assigned Managed Identity Name

stages:
- stage: BuildAndPush
  displayName: "Build & Push Docker Image"
  jobs:
  - job: BuildAndPushImage
    pool:
      name: linux-agent  # Ensure Docker is installed on the agent
    steps:

    # ✅ Authenticate to ACR using Managed Identity (No Secrets)
    - script: |
        az login --identity --client-id $(MANAGED_IDENTITY_NAME)
        az acr login --name $(ACR_NAME)
      displayName: "Login to ACR with Managed Identity"

     # ✅ Build the Docker Image
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) .
      displayName: "Build Docker Image"

    # ✅ Push the Image to ACR
    - script: |
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
      displayName: "Push Image to ACR"

    # ✅ Show Pushed Image
    - script: |
        az acr repository show-tags --name $(ACR_NAME) --repository $(IMAGE_NAME)
      displayName: "Verify Image in ACR"

