 - name: Check if Container App exists, create if not
      id: container_app_check
      run: |
        CONTAINER_APP_EXISTS=$(az containerapp show --name ${{ secrets.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$CONTAINER_APP_EXISTS" == "notfound" ]]; then
          echo "Container App not found. Creating..."
          az containerapp create \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --environment ${{ secrets.ENVIRONMENT_NAME }} \
            --image $IMAGE_TAG \
            --target-port 80 \
            --ingress external \
            --registry-server ${{ secrets.REGISTRY_NAME }}.azurecr.io \
            --query "name"
        else
          echo "Container App already exists."
        fi
