name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Checking secret
      run: echo '${{ secrets.AZURE_CREDENTIALS }}' | jq .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if ACR exists, create if not
      id: acr_check
      run: |
        ACR_EXISTS=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$ACR_EXISTS" == "notfound" ]]; then
          echo "ACR not found. Creating..."
          az acr create --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --sku Basic
        else
          echo "ACR already exists."
        fi

    - name: Authenticate to ACR (Required for Push)
      run: |
        az acr login --name ${{ secrets.REGISTRY_NAME }}

    - name: Build and Push Docker Image to ACR
      run: |
        IMAGE_TAG=${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Create Managed Identity if not exists
      id: managed_identity
      run: |
        MI_EXISTS=$(az identity show --name ${{ secrets.MANAGED_IDENTITY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$MI_EXISTS" == "notfound" ]]; then
          echo "Managed Identity not found. Creating..."
          az identity create --name ${{ secrets.MANAGED_IDENTITY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
        else
          echo "Managed Identity already exists."
        fi

    - name: Get Managed Identity Principal ID
      id: get_identity
      run: |
        PRINCIPAL_ID=$(az ide
