name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Checking secret
      run: echo '${{ secrets.AZURE_CREDENTIALS }}' | jq .

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if ACR exists, create if not
      id: acr_check
      run: |
        ACR_EXISTS=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$ACR_EXISTS" == "notfound" ]]; then
          echo "ACR not found. Creating..."
          az acr create --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --sku Basic
        else
          echo "ACR already exists."
        fi

    - name: Build and Push Docker Image to ACR
      run: |
        IMAGE_TAG=${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: Create Managed Identity if not exists
      id: managed_identity
      run: |
        MI_EXISTS=$(az identity show --name ${{ secrets.MANAGED_IDENTITY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$MI_EXISTS" == "notfound" ]]; then
          echo "Managed Identity not found. Creating..."
          az identity create --name ${{ secrets.MANAGED_IDENTITY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }}
        else
          echo "Managed Identity already exists."
        fi

    - name: Get Managed Identity Principal ID
      id: get_identity
      run: |
        PRINCIPAL_ID=$(az identity show --name ${{ secrets.MANAGED_IDENTITY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "principalId" --output tsv)
        echo "PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV

    - name: Get ACR Resource ID
      id: get_acr_id
      run: |
        ACR_ID=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "id" --output tsv)
        echo "ACR_ID=$ACR_ID" >> $GITHUB_ENV

    - name: Assign AcrPull Role to Managed Identity
      run: |
        az role assignment create --assignee ${{ env.PRINCIPAL_ID }} --role AcrPull --scope ${{ env.ACR_ID }} || echo "Role already assigned"

    - name: Check if Container App exists, create if not
      id: container_app_check
      run: |
        CONTAINER_APP_EXISTS=$(az containerapp show --name ${{ secrets.CONTAINER_APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        
        if [[ "$CONTAINER_APP_EXISTS" == "notfound" ]]; then
          echo "Container App not found. Creating..."
          az containerapp create \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --environment ${{ secrets.APP_ENVIRONMENT }} \
            --location ${{ secrets.LOCATION }} \
            --image ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }} \
            --registry-server ${{ secrets.REGISTRY_NAME }}.azurecr.io \
            --identity ${{ secrets.MANAGED_IDENTITY_NAME }} \
            --cpu 0.5 --memory 1Gi
            
          echo "Container App created successfully."
        else
          echo "Container App already exists."
        fi

    - name: Assign Managed Identity to Container App
      run: |
        az containerapp identity assign --name ${{ secrets.CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --user-assigned "/subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ManagedIdentity/userAssignedIdentities/${{ secrets.MANAGED_IDENTITY_NAME }}"

    - name: Deploy to Azure Container App
      run: |
        az containerapp update --name ${{ secrets.CONTAINER_APP_NAME }} \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --image ${{ env.IMAGE_TAG }}
