- name: Get ACR Resource ID
      id: get_acr_id
      run: |
        ACR_ID=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "id" --output tsv)
        echo "ACR_ID=$ACR_ID" >> $GITHUB_ENV

    # Assign AcrPull Role to Managed Identity
    - name: Assign AcrPull Role to Managed Identity
      run: |
        az role assignment create --assignee ${{ env.PRINCIPAL_ID }} --role AcrPull --scope ${{ env.ACR_ID }}
