name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers when code is pushed to the main branch
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build the app
      run: npm run build

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Check if ACR exists, create if not
    - name: Check if ACR exists, create if not
      id: acr_check
      run: |
        ACR_EXISTS=$(az acr show --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        if [[ "$ACR_EXISTS" == "notfound" ]]; then
          echo "ACR not found. Creating..."
          az acr create --name ${{ secrets.REGISTRY_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --sku Basic
        else
          echo "ACR already exists."
        fi

    # Authenticate to ACR
    - name: Authenticate to ACR
      run: az acr login --name ${{ secrets.REGISTRY_NAME }}

    # Build and Push Docker Image to ACR
    - name: Build and Push Docker Image to ACR
      run: |
        IMAGE_TAG=${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }}
        docker build -t $IMAGE_TAG .
        docker push $IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    # Check if Container App exists, create if not (with System-Assigned Identity)
    - name: Check if Container App exists, create if not
      id: container_app_check
      run: |
        CONTAINER_APP_EXISTS=$(az containerapp show --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "name" --output tsv || echo "notfound")
        
        if [[ "$CONTAINER_APP_EXISTS" == "notfound" ]]; then
          echo "Container App not found. Creating..."
          az containerapp create \
            --name ${{ secrets.APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --environment ${{ secrets.APP_ENVIRONMENT }} \
            --image ${{ secrets.REGISTRY_NAME }}.azurecr.io/myapp:${{ github.sha }} \
            --registry-server ${{ secrets.REGISTRY_NAME }}.azurecr.io \
            --system-assigned \
            --cpu 0.5 --memory 1Gi
            
          echo "Container App created successfully."
        else
          echo "Container App already exists."
        fi

    # Get System-Assigned Identity Principal ID
    - name: Get System-Assigned Identity Principal ID
      id: get_identity
      run: |
        PRINCIPAL_ID=$(az containerapp identity show --name ${{ secrets.APP_NAME }} --resource-group ${{ secrets.RESOURCE_GROUP }} --query "principalId" --output tsv)
        if [ -z "$PRINCIPAL_ID" ]; then
          echo "Error: System-Assigned Identity Principal ID is empty."
          exit 1
        fi
        echo "PRINCIPAL_ID=$PRINCIPAL_ID" >> $GITHUB_ENV

    # Assign AcrPull Role to System-Assigned Identity
    - name: Assign AcrPull Role to System-Assigned Identity
      run: |
        az role assignment create --assignee ${{ env.PRINCIPAL_ID }} --role AcrPull --scope /subscriptions/${{ secrets.SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP }}/providers/Microsoft.ContainerRegistry/registries/${{ secrets.REGISTRY_NAME }}
